/**
 * 사이드바를 만들면 다음을 할 수 있습니다.
 - 문서를 순서 있는 그룹으로 구성
 - 해당 그룹의 각 문서에 사이드바 렌더링
 - 이전/다음 탐색 제공

 사이드바는 파일 시스템에서 생성하거나 여기에서 명시적으로 정의할 수 있습니다.

 필요한 만큼 사이드바를 만들 수 있습니다.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // 기본적으로 Docusaurus는 docs 폴더 구조에서 사이드바를 생성합니다.
  integrationsSidebar: [
    { type: "doc", id: "integrations/index" },
    { type: "doc", id: "integrations/community" },
    {
      type: "category",
      label: "관측성",
      link: { type: "doc", id: "integrations/observability_index" },
      items: [
        {
          type: "category",
          label: "통합 기여하기",
          items: [
            {
              type: "autogenerated",
              dirName: "contribute_integration"
            }
          ],
        },
        {
          type: "autogenerated",
          dirName: "observability"
        },
      ],
    },
    {
      type: "category",
      label: "가드레일 프로바이더",
      link: {
        type: "generated-index",
        title: "가드레일 프로바이더",
        description: "LLM 호출에 안전성 검사와 콘텐츠 필터링을 추가합니다.",
        slug: "/guardrail_providers"
      },
      items: [
        {
          type: "category",
          label: "가드레일 기여하기",
          items: [
            "adding_provider/generic_guardrail_api",
            "adding_provider/simple_guardrail_tutorial",
            "adding_provider/adding_guardrail_support",
          ]
        },
        {
          type: "doc",
          id: "proxy/guardrails/team_based_guardrails",
          label: "팀별 자체 가드레일",
        },
        ...[
          "proxy/guardrails/qohash_qostodian_nexus",
          "proxy/guardrails/qualifire",
          "proxy/guardrails/aim_security",
          "proxy/guardrails/onyx_security",
          "proxy/guardrails/aporia_api",
          "proxy/guardrails/azure_content_guardrail",
          "proxy/guardrails/bedrock",
          "proxy/guardrails/crowdstrike_aidr",
          "proxy/guardrails/enkryptai",
          "proxy/guardrails/ibm_guardrails",
          "proxy/guardrails/grayswan",
          "proxy/guardrails/hiddenlayer",
          "proxy/guardrails/lasso_security",
          "proxy/guardrails/guardrails_ai",
          "proxy/guardrails/lakera_ai",
          "proxy/guardrails/model_armor",
          "proxy/guardrails/noma_security",
          "proxy/guardrails/dynamoai",
          "proxy/guardrails/openai_moderation",
          "proxy/guardrails/pangea",
          "proxy/guardrails/pillar_security",
          "proxy/guardrails/promptguard",
          "proxy/guardrails/pii_masking_v2",
          "proxy/guardrails/panw_prisma_airs",
          "proxy/guardrails/secret_detection",
          "proxy/guardrails/custom_guardrail",
          "proxy/guardrails/custom_code_guardrail",
          "proxy/guardrails/prompt_injection",
          "proxy/guardrails/tool_permission",
          "proxy/guardrails/rubrik",
          "proxy/guardrails/zscaler_ai_guard",
          "proxy/guardrails/javelin",
          "proxy/guardrails/akto",
        ].sort(),
      ],
    },
    {
      type: "category",
      label: "알림 및 모니터링",
      items: [
        "proxy/alerting",
        "proxy/pagerduty",
        "proxy/prometheus",
        "proxy/pyroscope_profiling"
      ]
    },
    {
      type: "category",
      label: "[베타] 프롬프트 관리",
      items: [
        {
          type: "category",
          label: "프롬프트 관리 기여하기",
          items: [
            "adding_provider/generic_prompt_management_api",
          ]
        },
        "proxy/litellm_prompt_management",
        "proxy/custom_prompt_management",
        "proxy/native_litellm_prompt",
        "proxy/prompt_management",
        "proxy/arize_phoenix_prompts"
      ]
    },
    {
      type: "category",
      label: "AI 도구",
      link: {
        type: "generated-index",
        title: "AI 도구",
        description: "OpenWebUI, Claude Code 등 AI 도구와 LiteLLM을 연동합니다.",
        slug: "/ai_tools"
      },
      items: [
        "tutorials/openweb_ui",
        {
          type: "category",
          label: "Claude Code",
          items: [
            "claude_code_compatibility",
            "tutorials/claude_responses_api",
            "tutorials/claude_code_max_subscription",
            "tutorials/claude_code_byok",
            "tutorials/claude_code_customer_tracking",
            "tutorials/claude_code_prompt_cache_routing",
            "tutorials/claude_code_websearch",
            "tutorials/claude_mcp",
            "tutorials/claude_non_anthropic_models",
            "tutorials/claude_code_plugin_marketplace",
            "tutorials/claude_code_beta_headers",
          ]
        },
        "tutorials/claude_desktop_cowork",
        "tutorials/opencode_integration",
        "tutorials/openclaw_integration",
        "tutorials/cursor_integration",
        "tutorials/github_copilot_integration",
        "tutorials/litellm_gemini_cli",
        "tutorials/litellm_qwen_code_cli",
        "tutorials/openai_codex",
        "tutorials/retool_assist",
        "tutorials/cost_tracking_coding"
      ]
    },
    {
      type: "category",
      label: "에이전트 SDK",
      link: {
        type: "generated-index",
        title: "에이전트 SDK",
        description: "에이전트 프레임워크와 SDK에서 LiteLLM을 사용합니다.",
        slug: "/agent_sdks"
      },
      items: [
        "tutorials/openai_agents_sdk",
        "tutorials/claude_agent_sdk",
        "tutorials/copilotkit_sdk",
        "tutorials/google_adk",
        "tutorials/google_genai_sdk",
        "tutorials/livekit_xai_realtime",
        "integrations/letta",
        { type: "doc", id: "tutorials/instructor", label: "LiteLLM에서 Instructor 사용" },
        { type: "doc", id: "langchain/langchain", label: "LiteLLM에서 LangChain 사용" },
        "projects/openai-agents"
      ]
    },
    {
      type: "category",
      label: "AI 에이전트로 관리",
      link: {
        type: "generated-index",
        title: "AI 에이전트로 관리",
        description: "AI 에이전트로 LiteLLM 배포를 관리합니다. 자연어로 사용자, 팀, 키, 모델 등을 생성할 수 있습니다.",
        slug: "/manage_with_ai_agents"
      },
      items: [
        "tutorials/claude_code_skills",
      ]
    },

  ],
  // 하지만 사이드바를 수동으로 만들 수도 있습니다.
  tutorialSidebar: [
    {
      type: "category",
      label: "한국어 핵심 가이드",
      collapsible: false,
      collapsed: false,
      items: [
        { type: "doc", id: "korean/index", label: "개요" },
        { type: "doc", id: "korean/sdk", label: "Python SDK" },
        { type: "doc", id: "korean/proxy", label: "Proxy / AI Gateway" },
        { type: "doc", id: "korean/providers", label: "프로바이더 / 모델" },
        { type: "doc", id: "korean/routing-observability-security", label: "라우팅 / 관측성 / 보안" },
        { type: "doc", id: "korean/operations-troubleshooting", label: "운영 / 문제 해결" },
        { type: "doc", id: "korean/release-notes-guide", label: "릴리즈 노트 읽는 법" },
      ],
    },
    // ════════════════════════════════════════════════════════════
    // GET STARTED
    // ════════════════════════════════════════════════════════════
    {
      type: "category",
      label: "시작하기",
      collapsible: false,
      collapsed: false,
      items: [
        { type: "doc", id: "index", label: "빠른 시작" },
        { type: "link", label: "모델 및 가격", href: "https://models.litellm.ai" },
        { type: "link", label: "변경 이력", href: "/litellm-docs-kr/release_notes" },
      ],
    },

    {
      type: "category",
      label: "LiteLLM Python SDK",
      items: [
        {
          type: "link",
          label: "빠른 시작",
          href: "/litellm-docs-kr/docs/#litellm-python-sdk",
        },
        {
          type: "category",
          label: "SDK 함수",
          items: [
            {
              type: "doc",
              id: "completion/input",
              label: "completion()",
            },
            {
              type: "doc",
              id: "embedding/supported_embedding",
              label: "embedding()",
            },
            {
              type: "doc",
              id: "response_api",
              label: "responses()",
            },
            {
              type: "doc",
              id: "text_completion",
              label: "text_completion()",
            },
            {
              type: "doc",
              id: "image_generation",
              label: "image_generation()",
            },
            {
              type: "doc",
              id: "completion/prompt_compression",
              label: "compress()",
            },
            {
              type: "doc",
              id: "audio_transcription",
              label: "transcription()",
            },
            {
              type: "doc",
              id: "text_to_speech",
              label: "speech()",
            },
            {
              type: "link",
              label: "전체 지원 엔드포인트 →",
              href: "https://docs.litellm.ai/docs/supported_endpoints",
            },
          ],
        },
        {
          type: "category",
          label: "설정",
          items: [
            "set_keys",
            "proxy_auth",
            "caching/all_caches",
          ],
        },
        "completion/token_usage",
        "exception_mapping",
      ],
    },
    {
      type: "category",
      label: "LiteLLM AI Gateway (Proxy)",
      link: {
        type: "generated-index",
        title: "LiteLLM AI Gateway (LLM Proxy)",
        description: `100개 이상의 LLM을 통합 인터페이스로 호출하고, 가상 키/사용자별 지출 추적 및 예산 설정을 지원하는 OpenAI 호환 Proxy Server(LLM Gateway)입니다.`,
        slug: "/simple_proxy",
      },
      items: [
        { type: "doc", id: "proxy/docker_quick_start", label: "시작하기 튜토리얼" },
        {
          type: "category",
          label: "Agent 및 MCP Gateway",
          items: [
            {
              type: "category",
              label: "A2A Agent Gateway",
              items: [
                "a2a",
                "a2a_invoking_agents",
                "a2a_agent_headers",
                "a2a_cost_tracking",
                "a2a_agent_permissions",
                "a2a_iteration_budgets",
              ],
            },
            {
              type: "category",
              label: "MCP Gateway",
              items: [
                "mcp",
                "mcp_usage",
                "mcp_openapi",
                "mcp_oauth",
                "mcp_obo_auth",
                "mcp_aws_sigv4",
                "mcp_zero_trust",
                "mcp_public_internet",
                "mcp_deployment",
                "mcp_semantic_filter",
                "mcp_control",
                "mcp_cost",
                "mcp_guardrail",
                "mcp_server_submissions",
                "mcp_toolsets",
                {
                  type: "link",
                  label: "MCP 문제 해결 가이드",
                  href: "/litellm-docs-kr/docs/mcp_troubleshoot"
                },
              ],
            },
            {
              type: "category",
              label: "Skills Gateway",
              items: [
                "skills_gateway",
              ],
            },
          ],
        },
        {
          "type": "category",
          "label": "Config.yaml 설정",
          "items": ["proxy/configs", "proxy/config_management", "proxy/config_settings"]
        },
        {
          type: "category",
          label: "설치 및 배포",
          items: [
            "proxy/quick_start",
            "proxy/cli",
            "proxy/debugging",
            "proxy/error_diagnosis",
            "proxy/deploy",
            "proxy/docker_image_security",
            "proxy/health",
            "proxy/master_key_rotations",
            "proxy/model_management",
            "proxy/prod",
            "proxy/worker_startup_hooks",
            "proxy/release_cycle",
          ],
        },
        {
          "type": "link",
          "label": "LiteLLM Cloud 데모",
          "href": "https://www.litellm.ai/cloud"
        },
        {
          type: "category",
          label: "관리자 UI",
          items: [
            "proxy/ui",
            {
              type: "category",
              label: "설정 및 SSO",
              items: [
                "proxy/admin_ui_sso",
                "proxy/ui/ui_edit_logo",
                "proxy/custom_sso",
                "proxy/custom_root_ui",
                "tutorials/scim_litellm",
              ]
            },
            {
              type: "category",
              label: "모델",
              items: [
                "proxy/ui_credentials",
                "proxy/ai_hub",
                "proxy/model_compare_ui",
                "proxy/ui_store_model_db_setting",
                "proxy/ui/routing_groups",
              ]
            },
            {
              type: "category",
              label: "팀 및 조직",
              items: [
                {
                  type: "link",
                  label: "역할 기반 접근 제어(RBAC) →",
                  href: "/litellm-docs-kr/docs/proxy/access_control"
                },
                "proxy/self_serve",
                "proxy/public_teams",
                "proxy/ui_project_management",
                "proxy/ui_search_tools",
                "proxy/ui/bulk_edit_users",
                "proxy/ui/page_visibility",
              ]
            },
            {
              type: "category",
              label: "관측성: 사용량",
              items: [
                "proxy/customer_usage",
                "proxy/endpoint_activity",
              ]
            },
            {
              type: "category",
              label: "로그",
              items: [
                "proxy/ui_logs",
                "proxy/ui_spend_log_settings",
                "proxy/ui_logs_sessions",
                "proxy/deleted_keys_teams",
              ]
            }
          ],
        },
        {
          type: "category",
          label: "아키텍처",
          items: [
            "proxy/architecture",
            "proxy/multi_tenant_architecture",
            "proxy/control_plane_and_data_plane",
            "proxy/high_availability_control_plane",
            "proxy/db_deadlocks",
            "proxy/db_info",
            "proxy/db_read_replica",
            "proxy/image_handling",
            "proxy/jwt_auth_arch",
            "proxy/spend_logs_deletion",
            "proxy/user_management_heirarchy",
            "router_architecture"
          ],
        },
        {
          type: "link",
          label: "전체 엔드포인트(Swagger)",
          href: "https://litellm-api.up.railway.app/",
        },
        {
          type: "category",
          label: "인증",
          items: [
            "proxy/virtual_keys",
            "proxy/token_auth",
            "proxy/jwt_key_mapping",
            "proxy/service_accounts",
            "proxy/access_control",
            "proxy/cli_sso",
            "proxy/custom_auth",
            "proxy/ip_address",
            "proxy/multiple_admins",
            "proxy/public_routes",
          ],
        },
        {
          type: "category",
          label: "예산 및 속도 제한",
          items: [
            "proxy/users",
            "proxy/team_budgets",
            "proxy/project_management",
            "proxy/ui_team_soft_budget_alerts",
            "proxy/tag_budgets",
            "proxy/customers",
            "proxy/dynamic_rate_limit",
            "proxy/rate_limit_tiers",
            "proxy/temporary_budget_increase",
            "proxy/budget_reset_and_tz",
          ],
        },
        "proxy/caching",
        "proxy/memory",
        {
          type: "category",
          label: "가드레일",
          items: [
            "proxy/guardrails/quick_start",
            "proxy/guardrails/team_based_guardrails",
            "proxy/guardrails/guardrail_load_balancing",
            "proxy/guardrails/test_playground",
            "proxy/guardrails/litellm_content_filter",
            "proxy/guardrails/realtime_guardrails",
            {
              type: "link",
              label: "프로바이더 →",
              href: "/litellm-docs-kr/docs/guardrail_providers",
            },
            {
              type: "category",
              label: "가드레일 기여하기",
              items: [
                "adding_provider/generic_guardrail_api",
                "adding_provider/simple_guardrail_tutorial",
                "adding_provider/adding_guardrail_support",
              ]
            },
          ],
        },
        {
          type: "category",
          label: "정책",
          items: [
            "proxy/guardrails/guardrail_policies",
            "proxy/guardrails/policy_flow_builder",
            "proxy/guardrails/policy_templates",
            "proxy/guardrails/policy_tags",
          ],
        },
        {
          type: "category",
          label: "커스텀 플러그인 만들기",
          description: "요청, 응답 등을 수정합니다.",
          items: [
            "proxy/call_hooks",
            "proxy/agentic_loop_hook",
            "proxy/rules",
          ]
        },
        "proxy/management_cli",
        {
          type: "link",
          label: "로드 밸런싱, 라우팅, 폴백",
          href: "https://docs.litellm.ai/docs/routing-load-balancing",
        },
        "traffic_mirroring",
        {
          type: "category",
          label: "로깅, 알림, 메트릭",
          items: [
            "proxy/dynamic_logging",
            "proxy/logging",
            "proxy/logging_spec",
            "proxy/team_logging",
            "proxy/email",
          ],
        },
        {
          type: "category",
          label: "LLM 요청 보내기",
          items: [
            "proxy/user_keys",
            "proxy/clientside_auth",
            "proxy/request_headers",
            "proxy/response_headers",
            "proxy/forward_client_headers",
            "proxy/model_discovery",
          ],
        },
        {
          type: "category",
          label: "모델 접근",
          items: [
            "proxy/model_access_guide",
            "proxy/model_access",
            "proxy/model_access_groups",
            "proxy/access_groups",
            "proxy/team_model_add",
            "proxy/credential_routing"
          ]
        },
        {
          type: "category",
          label: "시크릿 관리자",
          items: [
            "secret_managers/overview",
            "secret_managers/aws_secret_manager",
            "secret_managers/aws_kms",
            "secret_managers/azure_key_vault",
            "secret_managers/cyberark",
            "secret_managers/google_secret_manager",
            "secret_managers/google_kms",
            "secret_managers/hashicorp_vault",
            "secret_managers/custom_secret_manager",
            "oidc"
          ]
        },
        {
          type: "category",
          label: "비용 추적",
          items: [
            "proxy/cost_tracking",
            "tutorials/vertex_ai_pay_go",
            "proxy/request_tags",
            "proxy/custom_pricing",
            "proxy/pricing_calculator",
            "proxy/provider_margins",
            "proxy/provider_discounts",
            "proxy/sync_models_github",
            "proxy/billing",
          ],
        },
      ]
    },
    {
      type: "category",
      label: "지원 엔드포인트",
      link: {
        type: "generated-index",
        title: "지원 엔드포인트",
        description:
          "LiteLLM에서 여러 프로바이더 모델을 배포하고 호출하는 방법을 학습합니다.",
        slug: "/supported_endpoints",
      },
      items: [
        {
          type: "link",
          label: "/a2a - A2A 에이전트 Gateway",
          href: "/litellm-docs-kr/docs/a2a",
        },
        "assistants",
        "audio_transcription",
        "text_to_speech",
        {
          type: "category",
          label: "/batches",
          items: [
            "batches",
            "proxy/managed_batches",
          ]
        },
        "containers",
        "container_files",
        {
          type: "category",
          label: "/chat/completions",
          link: {
            type: "generated-index",
            title: "Chat Completions",
            description: "completion() 함수의 세부 동작을 설명합니다.",
            slug: "/completion",
          },
          items: [
            "completion/input",
            "completion/output",
            "completion/usage",
            "completion/http_handler_config",
          ],
        },
        "text_completion",
        "bedrock_converse",
        "embedding/supported_embedding",
        {
          type: "category",
          label: "/files",
          items: [
            "files_endpoints",
            "proxy/litellm_managed_files",
          ],
        },
        {
          type: "category",
          label: "/fine_tuning",
          items: [
            "fine_tuning",
            "proxy/managed_finetuning",
          ]
        },
        "evals_api",
        "generateContent",
        "apply_guardrail",
        "bedrock_invoke",
        "interactions",
        "memory_management",
        "image_edits",
        "image_generation",
        "image_variations",
        "videos",
        "vector_store_files",
        "vector_stores/create",
        "vector_stores/search",
        {
          type: "category",
          label: "/mcp - Model Context Protocol 안내",
          items: [
            "mcp",
            "mcp_usage",
            "mcp_openapi",
            "mcp_oauth",
            "mcp_obo_auth",
            "mcp_aws_sigv4",
            "mcp_zero_trust",
            "mcp_public_internet",
            "mcp_deployment",
            "mcp_semantic_filter",
            "mcp_control",
            "mcp_cost",
            "mcp_guardrail",
            "mcp_server_submissions",
            "mcp_zero_trust",
            "mcp_troubleshoot",
          ]
        },
        {
          type: "category",
          label: "/v1/messages",
          items: [
            "anthropic_unified/index",
            "anthropic_unified/structured_output",
            "anthropic_unified/messages_to_responses_mapping",
          ]
        },
        "anthropic_count_tokens",
        "moderation",
        "ocr",
        {
          type: "category",
          label: "Pass-through 엔드포인트 (Anthropic SDK 등)",
          items: [
            "pass_through/intro",
            "pass_through/anthropic_completion",
            "pass_through/assembly_ai",
            "pass_through/bedrock",
            "pass_through/azure_passthrough",
            "pass_through/cohere",
            "pass_through/cursor",
            "pass_through/google_ai_studio",
            "pass_through/langfuse",
            "pass_through/mistral",
            "pass_through/openai_passthrough",
            {
              type: "category",
              label: "Vertex AI",
              items: [
                "pass_through/vertex_ai",
                "pass_through/vertex_ai_live_websocket",
                "pass_through/vertex_ai_search_datastores",
              ]
            },
            "pass_through/vllm",
            "proxy/pass_through",
            "proxy/pass_through_guardrails"
          ]
        },
        "rag_ingest",
        "rag_query",
        "realtime",
        "proxy/realtime_webrtc",
        "rerank",
        "response_api",
        "prompt_management",
        "response_api_compact",
        {
          type: "category",
          label: "/search",
          items: [
            "search/index",
            "search/perplexity",
            "search/tavily",
            "search/exa_ai",
            "search/brave",
            "search/parallel_ai",
            "search/google_pse",
            "search/dataforseo",
            "search/firecrawl",
            "search/searxng",
            "search/linkup",
            "search/serper",
          ]
        },
        "skills",

      ],
    },
    {
      type: "category",
      label: "지원 모델 및 프로바이더",
      link: {
        type: "generated-index",
        title: "프로바이더",
        description:
          "LiteLLM에서 여러 프로바이더 모델을 배포하고 호출하는 방법을 학습합니다.",
        slug: "/providers",
      },
      items: [
        {
          type: "doc",
          id: "provider_registration/index",
          label: "모델 프로바이더로 통합",
        },
        {
          type: "doc",
          id: "contributing/adding_openai_compatible_providers",
          label: "OpenAI 호환 프로바이더 추가 (JSON)",
        },
        {
          type: "doc",
          id: "provider_registration/add_model_pricing",
          label: "모델 가격 및 context window 추가",
        },
        {
          type: "category",
          label: "OpenAI",
          items: [
            "providers/openai",
            "providers/openai/responses_api",
            "providers/openai/text_to_speech",
            "providers/openai/videos",
          ]
        },
        "providers/text_completion_openai",
        "providers/openai_compatible",
        {
          type: "category",
          label: "Azure OpenAI",
          items: [
            "providers/azure/azure",
            "providers/azure/azure_responses",
            "providers/azure/azure_embedding",
            "providers/azure/azure_speech",
            "providers/azure/videos",
          ]
        },
        {
          type: "category",
          label: "Azure AI",
          items: [
            "providers/azure_ai",
            "providers/azure_ai/azure_model_router",
            "providers/azure_ai_agents",
            "providers/azure_ocr",
            "providers/azure_document_intelligence",
            "providers/azure_ai_speech",
            "providers/azure_ai_img",
            "providers/azure_ai_vector_stores",
            "providers/azure_ai/azure_ai_vector_stores_passthrough",
          ]
        },
        {
          type: "category",
          label: "Vertex AI",
          items: [
            "providers/vertex",
            "providers/vertex_ai/videos",
            "providers/vertex_partner",
            "providers/vertex_self_deployed",
            "providers/vertex_embedding",
            "providers/vertex_image",
            "providers/vertex_speech",
            "providers/vertex_batch",
            "providers/vertex_ocr",
            "providers/vertex_ai_agent_engine",
            "providers/vertex_realtime",
          ]
        },
        {
          type: "category",
          label: "Google AI Studio",
          items: [
            "providers/gemini",
            "providers/gemini/videos",
            "providers/gemini/music",
            "providers/google_ai_studio/files",
            "providers/google_ai_studio/image_gen",
            "providers/google_ai_studio/realtime",
          ]
        },
        "providers/anthropic",
        "providers/anthropic_tool_search",
        "providers/aws_sagemaker",
        {
          type: "category",
          label: "Bedrock",
          items: [
            "providers/bedrock",
            "providers/bedrock_embedding",
            "providers/bedrock_imported",
            "providers/bedrock_image_gen",
            "providers/bedrock_rerank",
            "providers/bedrock_agentcore",
            "providers/bedrock_agents",
            "providers/bedrock_writer",
            "providers/bedrock_batches",
            "providers/bedrock_realtime_with_audio",
            "providers/aws_polly",
            "providers/bedrock_vector_store",
            "providers/bedrock_mantle",
          ]
        },
        "providers/litellm_proxy",
        "providers/abliteration",
        "providers/ai21",
        "providers/aiml",
        "providers/aleph_alpha",
        "providers/amazon_nova",
        "providers/anyscale",
        "providers/apertis",
        "providers/baseten",
        "providers/black_forest_labs",
        "providers/black_forest_labs_img_edit",
        "providers/bytez",
        "providers/cerebras",
        "providers/chutes",
        "providers/clarifai",
        "providers/cloudflare_workers",
        "providers/codestral",
        "providers/cohere",
        "providers/cometapi",
        "providers/compactifai",
        "providers/custom_llm_server",
        "providers/dashscope",
        "providers/databricks",
        "providers/datarobot",
        "providers/deepgram",
        "providers/deepinfra",
        "providers/deepseek",
        "providers/docker_model_runner",
        "providers/elevenlabs",
        "providers/fal_ai",
        "providers/featherless_ai",
        "providers/fireworks_ai",
        "providers/friendliai",
        "providers/galadriel",
        "providers/github",
        "providers/github_copilot",
        "providers/gmi",
        "providers/chatgpt",
        "providers/gradient_ai",
        "providers/groq",
        "providers/helicone",
        "providers/heroku",
        {
          type: "category",
          label: "HuggingFace",
          items: [
            "providers/huggingface",
            "providers/huggingface_rerank",
          ]
        },
        "providers/hyperbolic",
        "providers/infinity",
        "providers/jina_ai",
        "providers/lambda_ai",
        "providers/langgraph",
        "providers/lemonade",
        "providers/llamafile",
        "providers/llamagate",
        "providers/lm_studio",
        "providers/manus",
        "providers/meta_llama",
        "providers/milvus_vector_stores",
        "providers/mistral",
        "providers/minimax",
        "providers/moonshot",
        "providers/morph",
        "providers/nebius",
        "providers/nlp_cloud",
        "providers/nano-gpt",
        "providers/novita",
        { type: "doc", id: "providers/nscale", label: "Nscale (EU Sovereign)" },
        {
          type: "category",
          label: "Nvidia NIM",
          items: [
            "providers/nvidia_nim",
            "providers/nvidia_nim_rerank",
          ]
        },
        "providers/nvidia_riva",
        "providers/oci",
        "providers/ollama",
        "providers/openrouter",
        "providers/sarvam",
        "providers/ovhcloud",
        {
          type: "category",
          label: "Perplexity AI",
          items: [
            "providers/perplexity",
            "providers/perplexity_embedding",
          ]
        },
        "providers/petals",
        "providers/poe",
        "providers/publicai",
        "providers/predibase",
        "providers/pydantic_ai_agent",
        "providers/ragflow",
        "providers/recraft",
        "providers/replicate",
        {
          type: "category",
          label: "RunwayML",
          items: [
            "providers/runwayml/images",
            "providers/runwayml/videos",
          ]
        },
        "providers/sambanova",
        "providers/sap",
        "providers/scaleway",
        "providers/stability",
        "providers/synthetic",
        "providers/snowflake",
        "providers/togetherai",
        "providers/topaz",
        "providers/triton-inference-server",
        "providers/v0",
        "providers/vercel_ai_gateway",
        {
          type: "category",
          label: "vLLM",
          items: [
            "providers/vllm",
            "providers/vllm_batches",
          ]
        },
        "providers/volcano",
        "providers/voyage",
        "providers/wandb_inference",
        {
          type: "category",
          label: "WatsonX",
          items: [
            "providers/watsonx/index",
            "providers/watsonx/audio_transcription",
          ]
        },
        {
          type: "category",
          label: "xAI",
          items: [
            "providers/xai",
            "providers/xai_realtime",
          ]
        },
        "providers/xiaomi_mimo",
        "providers/xinference",
        "providers/zai",
      ],
    },


    {
      type: "category",
      label: "라우팅 및 부하 분산",
      link: {
        type: "generated-index",
        title: "라우팅 및 부하 분산",
        description: "LLM 요청에 대한 부하 분산, 라우팅, 폴백 설정 방법을 학습합니다.",
        slug: "/routing-load-balancing",
      },
      items: [
        "routing",
        "adaptive_router",
        "scheduler",
        "proxy/auto_routing",
        "proxy/load_balancing",
        "proxy/keys_teams_router_settings",
        "proxy/provider_budget_routing",
        "proxy/reliability",
        "proxy/fallback_management",
        "proxy/tag_routing",
        "proxy/timeout",
        "wildcard_routing",
        "proxy/health_check_routing"
      ],
    },
    "benchmarks",
    {
      type: "category",
      label: "기여하기",
      items: [
        "extras/contributing_code",
        {
          type: "category",
          label: "프로바이더 추가",
          items: [
            "contributing/adding_openai_compatible_providers",
            "adding_provider/directory_structure",
            "adding_provider/new_rerank_provider",
          ]
        },
        "extras/contributing",
        "contributing",
      ]
    },
    {
      type: "category",
      label: "기타",
      items: [
        "sdk_custom_pricing",
        "migration",
        "data_security",
        "data_retention",
        "proxy/security_encryption_faq",
        "migration_policy",
        "load_test_advanced",
        "load_test_sdk",
        "load_test_rpm",
        {
          type: "category",
          label: "❤️ 🚅 LiteLLM 기반 프로젝트",
          link: {
            type: "generated-index",
            title: "LiteLLM 기반 프로젝트",
            description:
              "LiteLLM에서 여러 프로바이더의 모델을 배포하고 호출하는 방법을 학습합니다.",
            slug: "/project",
          },
          items: [
            "projects/smolagents",
            "projects/mini-swe-agent",
            "projects/openai-agents",
            "projects/Google ADK",
            "projects/Agent Lightning",
            "projects/Harbor",
            "projects/GraphRAG",
            "projects/Docq.AI",
            "projects/PDL",
            "projects/OpenInterpreter",
            "projects/Elroy",
            "projects/dbally",
            "projects/FastREPL",
            "projects/PROMPTMETHEUS",
            "projects/Codium PR Agent",
            "projects/Prompt2Model",
            "projects/SalesGPT",
            "projects/Softgen",
            "projects/Quivr",
            "projects/Langstream",
            "projects/Otter",
            "projects/YiVal",
            "projects/llm_cord",
            "projects/pgai",
            "projects/GPTLocalhost",
            "projects/HolmesGPT",
            "projects/Railtracks",
          ],
        },
        "extras/code_quality",
        "rules",
        "proxy/team_based_routing",
        "proxy/customer_routing",
        "proxy_server",
      ],
    },
    {
      type: "category",
      label: "문제 해결",
      items: [
        "troubleshoot/ui_issues",
        "troubleshoot/cost_discrepancy",
        "mcp_troubleshoot",
        {
          type: "category",
          label: "성능 / 지연 시간",
          items: [
            "troubleshoot/latency_overhead",
            "troubleshoot/cpu_issues",
            "troubleshoot/memory_issues",
            "troubleshoot/spend_queue_warnings",
            "troubleshoot/max_callbacks",
            "troubleshoot/prisma_migrations",
          ],
        },
        "troubleshoot/pip_venv_upgrade",
        "troubleshoot/rollback",
        "troubleshoot",
      ],
    },
  ],
};

const learnSidebar = {
  learnSidebar: [
    // ── Landing page ──────────────────────────────────────────────────
    { type: "doc", id: "learn/index", label: "학습" },
    {
      type: "category",
      label: "여기서 시작",
      collapsible: true,
      collapsed: false,
      items: [
        "learn/sdk_quickstart",
        "learn/gateway_quickstart",
      ],
    },

    // ── 가이드 ────────────────────────────────────────────────────────
    {
      type: "category",
      label: "가이드",
      collapsible: true,
      collapsed: false,
      link: { type: "doc", id: "guides/index" },
      items: [
        {
          type: "category",
          label: "핵심 요청",
          collapsible: true,
          collapsed: false,
          link: {
            type: "generated-index",
            title: "핵심 요청",
            description: "스트리밍, 배칭, 구조화 출력, reasoning 동작을 다룹니다.",
            slug: "/guides/core_request_response_patterns"
          },
          items: [
            "completion/stream",
            "completion/batching",
            "completion/json_mode",
            "reasoning_content",
          ],
        },
        {
          type: "category",
          label: "도구 호출",
          collapsible: true,
          collapsed: true,
          link: {
            type: "generated-index",
            title: "도구 호출",
            description: "함수 호출, 웹 도구, 가로채기 패턴, computer use, 코드 인터프리터, 도구 호출 관리 방식을 다룹니다.",
            slug: "/guides/tools_integrations"
          },
          items: [
            "completion/function_call",
            "completion/web_search",
            {
              type: "doc",
              id: "integrations/websearch_interception",
              label: "웹 검색 가로채기",
            },
            "completion/web_fetch",
            "completion/computer_use",
            "guides/code_interpreter",
            "completion/anthropic_advisor_tool",
            "completion/message_sanitization",
          ],
        },
        {
          type: "category",
          label: "멀티모달 I/O",
          collapsible: true,
          collapsed: true,
          link: {
            type: "generated-index",
            title: "멀티모달 I/O",
            description: "비전, 오디오, PDF, 이미지 생성, 비디오 생성을 다룹니다.",
            slug: "/guides/multimodal_io"
          },
          items: [
            "completion/vision",
            "completion/audio",
            "completion/document_understanding",
            "completion/image_generation_chat",
            "proxy/veo_video_generation",
          ],
        },
        {
          type: "category",
          label: "검색 및 지식",
          collapsible: true,
          collapsed: true,
          link: {
            type: "generated-index",
            title: "검색 및 지식",
            description: "벡터 스토어, 파일 검색, 인용, 지식 기반 라우팅을 다룹니다.",
            slug: "/guides/retrieval_knowledge"
          },
          items: [
            "completion/knowledgebase",
          ],
        },
        {
          type: "category",
          label: "프롬프트 및 컨텍스트",
          collapsible: true,
          collapsed: true,
          link: {
            type: "generated-index",
            title: "프롬프트 및 컨텍스트",
            description: "프롬프트 캐싱, 트리밍, 포맷팅, assistant prefill, 예측 출력을 다룹니다.",
            slug: "/guides/prompts_context"
          },
          items: [
            "completion/prefix",
            "completion/predict_outputs",
            "completion/prompt_compression",
            "completion/message_trimming",
            "completion/prompt_caching",
            "completion/prompt_formatting",
          ],
        },
        {
          type: "category",
          label: "호환성 및 확장성",
          collapsible: true,
          collapsed: true,
          link: {
            type: "generated-index",
            title: "호환성 및 확장성",
            description: "프로바이더별 파라미터, 모델 별칭, fine-tuned 모델, 어댑터를 다룹니다.",
            slug: "/guides/compatibility_extensibility"
          },
          items: [
            "completion/provider_specific_params",
            "completion/drop_params",
            "completion/model_alias",
            "guides/finetuned_models",
            "extras/creating_adapters",
          ],
        },
        {
          type: "category",
          label: "신뢰성, 테스트 및 비용",
          collapsible: true,
          collapsed: true,
          link: {
            type: "generated-index",
            title: "신뢰성, 테스트 및 비용",
            description: "재시도, 폴백, 모의 응답, 예산 제어를 다룹니다.",
            slug: "/guides/reliability_testing_spend"
          },
          items: [
            "completion/mock_requests",
            "completion/reliable_completions",
            "budget_manager",
          ],
        },
        {
          type: "category",
          label: "보안 및 네트워크",
          collapsible: true,
          collapsed: true,
          link: {
            type: "generated-index",
            title: "보안 및 네트워크",
            description: "SSL, 커스텀 CA 번들, HTTP 프록시 설정, 서비스별 검증을 다룹니다.",
            slug: "/guides/security_network"
          },
          items: [
            "guides/security_settings",
          ],
        },
      ],
    },

    // ── 튜토리얼 ─────────────────────────────────────────────────────
    {
      type: "category",
      label: "튜토리얼",
      collapsible: true,
      collapsed: false,
      link: { type: "doc", id: "tutorials/index" },
      items: [
        {
          type: "category",
          label: "시작하기",
          collapsed: false,
          link: {
            type: "generated-index",
            title: "시작하기",
            description: "설치, playground, text completion, mock completion을 다룹니다.",
            slug: "/tutorials/getting_started"
          },
          items: [
            "tutorials/installation",
            "tutorials/first_playground",
            "tutorials/text_completion",
            "tutorials/mock_completion",
          ],
        },
        {
          type: "link",
          label: "에이전트 SDK 및 프레임워크",
          href: "/litellm-docs-kr/docs/agent_sdks",
        },
        {
          type: "link",
          label: "AI 코딩 도구",
          href: "/litellm-docs-kr/docs/ai_tools",
        },
        {
          type: "category",
          label: "Python SDK",
          collapsed: true,
          link: {
            type: "generated-index",
            title: "Python SDK",
            description: "Proxy 서버 없이 Python SDK만 사용하는 튜토리얼입니다.",
            slug: "/tutorials/python_sdk"
          },
          items: [
            "tutorials/gradio_integration",
            "tutorials/provider_specific_params",
            "tutorials/model_fallbacks",
            "tutorials/fallbacks",
          ],
        },
        {
          type: "category",
          label: "프로바이더 설정",
          collapsed: true,
          link: {
            type: "generated-index",
            title: "프로바이더 설정",
            description: "Azure OpenAI, HuggingFace, TogetherAI, 로컬 모델 등과 LiteLLM을 연결합니다.",
            slug: "/tutorials/provider_tutorials"
          },
          items: [
            "tutorials/azure_openai",
            "tutorials/TogetherAI_liteLLM",
            "tutorials/huggingface_tutorial",
            "tutorials/huggingface_codellama",
            "tutorials/finetuned_chat_gpt",
            "tutorials/oobabooga",
          ],
        },
        {
          type: "category",
          label: "Proxy: 관리자 및 접근",
          collapsed: true,
          link: {
            type: "generated-index",
            title: "Proxy: 관리자 및 접근",
            description: "사용자/팀 관리, SSO, SCIM, 라우팅 규칙을 다룹니다.",
            slug: "/tutorials/proxy_admin_access"
          },
          items: [
            "tutorials/default_team_self_serve",
            "tutorials/msft_sso",
            "tutorials/scim_litellm",
            "tutorials/tag_management",
          ],
        },
        {
          type: "category",
          label: "Proxy: 기능 및 안전성",
          collapsed: true,
          link: {
            type: "generated-index",
            title: "Proxy: 기능 및 안전성",
            description: "프롬프트 캐싱, passthrough API, realtime, 가드레일, PII 마스킹을 다룹니다.",
            slug: "/tutorials/proxy_features_safety"
          },
          items: [
            "tutorials/prompt_caching",
            "tutorials/file_search_responses_api",
            "tutorials/anthropic_file_usage",
            "tutorials/gemini_realtime_with_audio",
            "tutorials/litellm_proxy_aporia",
            "tutorials/presidio_pii_masking",
          ],
        },
        {
          type: "category",
          label: "관측성 및 평가",
          collapsed: true,
          link: {
            type: "generated-index",
            title: "관측성 및 평가",
            description: "로깅, 모니터링, 벤치마킹, 평가 스위트를 다룹니다.",
            slug: "/tutorials/observability_evaluation"
          },
          items: [
            "tutorials/elasticsearch_logging",
            "tutorials/compare_llms",
            "tutorials/litellm_Test_Multiple_Providers",
            "tutorials/eval_suites",
            "tutorials/lm_evaluation_harness",
          ],
        },
      ],
    },
  ],
};

module.exports = { ...sidebars, ...learnSidebar };
